### ISSUE TITLE
Publish the CFPB-specific regulation tweaks

### ISSUE THREAD

**Issue by cmc333333** [cfpb/regulations-parser#266]
There were numerous minor changes to reg E and reg Z's XML files to aid the parser. IIRC, those weren't published because we wanted to wait for the application's launch.

Any chance you all can publish them now? They'd make "this is how you parse a reg" tutorials a bit easier as we could start with reg E. @micahsaul put together a similar repo for FEC: https://github.com/micahsaul/fec_docs , but the CFPB docs no doubt have a much more illustrative history of the types of changes that need to be made.

**Comment by willbarton** [comment]
These changes should be in the now-public [fr-notices](https://github.com/cfpb/fr-notices) repo.

**Comment by ascott1** [comment]
Indeed they are. Closing!
