### ISSUE TITLE
Is build_by_notice used?

### ISSUE THREAD

**Issue by cmc333333** [cfpb/regulations-parser#306]
Per a conversation with @willbarton, I took a stab at importing some of the `eregs` runner commits into CFPB's repo. I'm just about done, but when I tried splitting apart the "build_by_notice" command/operation, I found that is relies on a variable which doesn't exist: https://github.com/cfpb/regulations-parser/blob/44baeafb788b74f4fccbc93d67c62bb9e0dea016/build_from.py#L133

Is this command every used? If not, I'll just remove it and proceed. If so, I can fix it up to add the appropriate parameter.

**Comment by willbarton** [comment]
I think it can be removed for now... we can always use the git history to cobble it back together if we see that we need it.

**Comment by cmc333333** [comment]
Excellent, thanks!
